#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamBodyFit.Resource", IsApplication=true)]

namespace XamBodyFit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int bg_login = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int bg_main = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int bg_register = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int btn_Activate_bg = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int btn_FacebookLike_bg = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int btn_Recover_bg = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int btn_Train_bg = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int btn_WatchUs_bg = 2130968594;
			
			// aapt resource value: 0x7f040009
			public const int btn_login = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int btn_login_bg = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int btn_logut_bg = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int btn_remember_me = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int input_login = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int input_login_hint = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int input_register = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int input_register_bg = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int input_register_hint = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int lbl_name = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int white = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int activate = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_up = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_emailicon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_pwdicon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int likewatch = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int maximize = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menu = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int monoandroidsplash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int play = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int recover = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int share = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splash_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int train = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int watchus = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int SampleVideoView = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int TextView01 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int btnActivate = 2131165186;
			
			// aapt resource value: 0x7f070013
			public const int btnAlready = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int btnEmail = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int btnFacebook = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int btnFacebookLike = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int btnForgotPassword = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int btnLogin = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int btnRecover = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int btnRegister = 2131165209;
			
			// aapt resource value: 0x7f070003
			public const int btnTrain = 2131165187;
			
			// aapt resource value: 0x7f070016
			public const int btnWatchUs = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int chkRememberMe = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int imgViewLogo = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int imgViewThumbnail = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int mainContainer = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int mainImageView = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int myListView = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int parentContainer = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int txtDescription = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int txtDuration = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int txtEmail = 2131165195;
			
			// aapt resource value: 0x7f070017
			public const int txtFirstName = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int txtLastName = 2131165208;
			
			// aapt resource value: 0x7f07000c
			public const int txtPassword = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int txtTitle = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int catalog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int catalog_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int register = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int splash = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int btn_forgot_password = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int btn_link_to_login = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int btn_link_to_register = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int btn_login = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int btn_logout = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int btn_register = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int hint_email = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int hint_firstName = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hint_lastName = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int hint_password = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int name = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int welcome = 2131034123;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Mono_Android_Theme_Splash = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
